on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: tedeshpaacr1.azurecr.io
        username: ${{ secrets.acr_tedeshpaacr1_username }}
        password: ${{ secrets.acr_tedeshpaacr1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app dir/WindowsMvcApp" -f  "app dir/WindowsMvcApp/Dockerfile" -t tedeshpaacr1.azurecr.io/jamindaaks2:${{ github.sha }}
        docker push tedeshpaacr1.azurecr.io/jamindaaks2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_jamindaaks2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jamindaaks2763b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jamindaaks2763b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jamindaaks2763b
        container-registry-url: tedeshpaacr1.azurecr.io
        container-registry-username: ${{ secrets.acr_tedeshpaacr1_username }}
        container-registry-password: ${{ secrets.acr_tedeshpaacr1_password }}
        secret-name: jamindaaks2dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: jamindaaks2763b
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          tedeshpaacr1.azurecr.io/jamindaaks2:${{ github.sha }}
        imagepullsecrets: |
          jamindaaks2dockerauth